# Generated by Django 4.1.4 on 2022-12-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('birth_date', models.DateField(default='2000-01-01')),
                ('pesel', models.CharField(max_length=11, unique=True)),
                ('driver_licence_number', models.CharField(max_length=13, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(choices=[('SUV', 'Suv'), ('MINIBUS', 'Minibus'), ('LIMOUSINE', 'Limousine'), ('COUPE', 'Coupe'), ('KOMBI', 'Kombi'), ('CITY CARS', 'City Cars')], default='CITY CARS', max_length=15)),
                ('status', models.BooleanField(blank=True, default=1, editable=False, verbose_name='Is vehicle available?')),
                ('mark', models.CharField(max_length=45)),
                ('model', models.CharField(max_length=45)),
                ('price_per_day', models.IntegerField()),
            ],
        ),
    ]
