# Generated by Django 4.1.4 on 2022-12-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalCarSystemGraphQL', '0003_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='driver_licence_number',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='pesel',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
