# Generated by Django 4.1.4 on 2022-12-19 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalCarSystemGraphQL', '0004_alter_client_driver_licence_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalCarSystemGraphQL.client'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalCarSystemGraphQL.vehicle'),
        ),
    ]
