# Generated by Django 4.1.3 on 2022-11-08 20:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import rentalCarSystem.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)])),
                ('town', models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(45)])),
                ('country', models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(45)])),
                ('street', models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(60)])),
                ('apartment_number', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(7)])),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(2)])),
                ('birth_date', models.DateField(default='2000-01-01')),
                ('pesel', models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MinLengthValidator(11)])),
                ('driver_licence_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MinLengthValidator(11)])),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MinLengthValidator(15)])),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='rentalCarSystem.address')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.BooleanField(blank=True, default=1, null=True, verbose_name='Was payed by cash?')),
                ('card_number', models.CharField(blank=True, max_length=45, null=True, verbose_name='Card number [if cash unchecked]')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_production', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022)),
                ('license_plate_number', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(6)])),
                ('vin_number', models.CharField(max_length=17, validators=[django.core.validators.MinLengthValidator(17)])),
                ('date_of_the_review', models.DateField()),
                ('condition_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300000)])),
                ('last_service', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(5000), django.core.validators.MaxValueValidator(300000)])),
            ],
            options={
                'verbose_name_plural': 'Vehicle Informations',
            },
        ),
        migrations.CreateModel(
            name='VehicleSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(2)])),
                ('gear_box', models.CharField(choices=[('AUTO', 'Auto'), ('MANUAL', 'Manual')], default='AUTO', max_length=7)),
                ('type_of_drive', models.CharField(choices=[('FWD', 'FWD'), ('RWD', 'RWD'), ('AWD', 'AWD')], default='FWD', max_length=4)),
                ('type_of_fuel', models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], default='DIESEL', max_length=11)),
                ('avg_fuel_consumption', models.FloatField(default=10.0, max_length=4, verbose_name='Average fuel consumption per 100km [L]')),
                ('num_of_doors', models.SmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)], verbose_name='Number of doors')),
                ('num_of_seats', models.SmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(9)], verbose_name='Number of seats')),
                ('boot_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(2000)], verbose_name='Boot Capacity')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Specifications',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(choices=[('SUV', 'Suv'), ('MINIBUS', 'Minibus'), ('LIMOUSINE', 'Limousine'), ('COUPE', 'Coupe'), ('KOMBI', 'Kombi'), ('CITY CARS', 'City Cars')], default='CITY CARS', max_length=15)),
                ('status', models.BooleanField(blank=True, default=1, verbose_name='Is vehicle available?')),
                ('mark', models.CharField(max_length=45)),
                ('model', models.CharField(max_length=45)),
                ('price_per_day', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(7500)])),
                ('vehicle_information', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='rentalCarSystem.vehicleinformation')),
                ('vehicle_specification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='rentalCarSystem.vehiclespecification')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_start_date', models.DateField(validators=[rentalCarSystem.models.present_date_validator])),
                ('rent_end_date', models.DateField()),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_in_perc', models.SmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('deposit', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(100000)])),
                ('km_limit', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)])),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='rentalCarSystem.client')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rentalCarSystem.payment')),
                ('vehicle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='rentalCarSystem.vehicle')),
            ],
        ),
    ]
