# Generated by Django 4.1.2 on 2022-10-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=6)),
                ('town', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('street', models.CharField(max_length=45)),
                ('apartment_number', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('birth_date', models.DateField()),
                ('pesel', models.CharField(max_length=11, unique=True)),
                ('driver_licence_number', models.CharField(max_length=13, unique=True)),
                ('phone_numer', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.SmallIntegerField()),
                ('card_number', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_start_date', models.DateField()),
                ('rent_end_date', models.DateField()),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_in_perc', models.SmallIntegerField()),
                ('deposit', models.IntegerField()),
                ('km_limit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField()),
                ('model', models.CharField(max_length=45)),
                ('mark', models.CharField(max_length=45)),
                ('price_per_day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=45)),
                ('avg_fuel_consumption', models.FloatField(max_length=4)),
                ('boot_capacity', models.IntegerField()),
                ('num_of_doors', models.SmallIntegerField()),
                ('num_of_seats', models.SmallIntegerField()),
            ],
        ),
    ]
