# Generated by Django 4.1.2 on 2022-10-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalCarSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='deposit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='discount_in_perc',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
