# Generated by Django 4.1.2 on 2022-10-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalCarSystem', '0003_client_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='car_type',
            field=models.CharField(choices=[('SUV', 'Suv'), ('MINIBUS', 'Minibus'), ('LIMUZYNA', 'Limuzyna'), ('COUPE', 'Coupe'), ('KOMBI', 'Kombi')], default='KOMBI', max_length=10),
        ),
        migrations.AddField(
            model_name='vehiclespecification',
            name='gear_box',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Auto')], default='MANUAL', max_length=7),
        ),
        migrations.AddField(
            model_name='vehiclespecification',
            name='type_of_drive',
            field=models.CharField(choices=[('FWD', 'FWD'), ('RWD', 'RWD'), ('AWD', 'AWD')], default='FWD', max_length=4),
        ),
        migrations.AddField(
            model_name='vehiclespecification',
            name='type_of_fuel',
            field=models.CharField(choices=[('DIESEL', 'Diesel'), ('BENZYNA', 'Benzyna'), ('ELEKTRYCZNY', 'Elektryczny'), ('HYBRYDA', 'Hybryda')], default='DIESEL', max_length=11),
        ),
    ]
