# Generated by Django 4.1.2 on 2022-10-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalCarSystem', '0004_vehicle_car_type_vehiclespecification_gear_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Card number [if cash unchecked]'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cash',
            field=models.BooleanField(blank=True, default=1, null=True, verbose_name='Was payed by cash?'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.BooleanField(blank=True, default=1, verbose_name='Is vehicle available?'),
        ),
        migrations.AlterField(
            model_name='vehiclespecification',
            name='gear_box',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('MANUAL', 'Manual')], default='MANUAL', max_length=7),
        ),
    ]
