# Generated by Django 4.1.3 on 2022-11-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalCarSystem', '0007_alter_rent_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='deposit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
