# Generated by Django 4.1.2 on 2022-10-26 13:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalCarSystem', '0008_alter_client_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalCarSystem.address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='apartment_number',
            field=models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(60)]),
        ),
        migrations.AlterField(
            model_name='address',
            name='town',
            field=models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='rent',
            name='deposit',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='rent',
            name='discount_in_perc',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='rent',
            name='km_limit',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price_per_day',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='license_plate_number',
            field=models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='mileage',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='vin_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.MinLengthValidator(17)]),
        ),
        migrations.AlterField(
            model_name='vehiclespecification',
            name='boot_capacity',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='vehiclespecification',
            name='color',
            field=models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='vehiclespecification',
            name='num_of_doors',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='vehiclespecification',
            name='num_of_seats',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
