# Generated by Django 4.1.2 on 2022-10-26 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalCarSystem', '0009_client_adress_alter_address_apartment_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='adress',
        ),
        migrations.AlterField(
            model_name='address',
            name='apartment_number',
            field=models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_numer',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MinLengthValidator(15)]),
        ),
        migrations.AlterField(
            model_name='rent',
            name='deposit',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='rent',
            name='discount_in_perc',
            field=models.SmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99), django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(2)]),
        ),
    ]
