# Generated by Django 4.1.2 on 2022-10-30 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalCarSystem', '0010_remove_client_adress_alter_address_apartment_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='vehicleinformation',
            options={'verbose_name_plural': 'Vehicle Informations'},
        ),
        migrations.AlterModelOptions(
            name='vehiclespecification',
            options={'verbose_name_plural': 'Vehicle Specifications'},
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price_per_day',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(7500)]),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='last_service',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(5000), django.core.validators.MaxValueValidator(300000)]),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='mileage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300000)]),
        ),
        migrations.AlterField(
            model_name='vehiclespecification',
            name='avg_fuel_consumption',
            field=models.FloatField(default=10.0, max_length=4, verbose_name='Average fuel consumption per 100km [L]'),
        ),
        migrations.AlterField(
            model_name='vehiclespecification',
            name='boot_capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(2000)], verbose_name='Boot Capacity'),
        ),
        migrations.AlterField(
            model_name='vehiclespecification',
            name='gear_box',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('MANUAL', 'Manual')], default='AUTO', max_length=7),
        ),
        migrations.AlterField(
            model_name='vehiclespecification',
            name='num_of_doors',
            field=models.SmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)], verbose_name='Number of doors'),
        ),
        migrations.AlterField(
            model_name='vehiclespecification',
            name='num_of_seats',
            field=models.SmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(9)], verbose_name='Number of seats'),
        ),
        migrations.AlterField(
            model_name='vehiclespecification',
            name='type_of_fuel',
            field=models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], default='DIESEL', max_length=11),
        ),
    ]
