# Generated by Django 4.1.3 on 2022-11-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalCarSystem', '0013_alter_vehicleinformation_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.BooleanField(blank=True, default=1, editable=False, verbose_name='Is vehicle available?'),
        ),
    ]
