# Generated by Django 4.1.2 on 2022-10-31 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalCarSystem', '0014_alter_client_address1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalCarSystem.address'),
        ),
    ]
