# Generated by Django 4.1.3 on 2022-11-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalCarSystem', '0014_alter_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='full_name',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
    ]
