# Generated by Django 4.1.3 on 2022-11-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalCarSystem', '0015_alter_vehicle_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='number_of_days',
            field=models.CharField(blank=True, editable=False, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='price_per_day',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
