# Generated by Django 4.1.2 on 2022-10-31 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalCarSystem', '0016_alter_client_address1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='address1',
            new_name='address',
        ),
        migrations.AddField(
            model_name='rent',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalCarSystem.client'),
        ),
        migrations.AddField(
            model_name='rent',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalCarSystem.payment'),
        ),
        migrations.AddField(
            model_name='rent',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalCarSystem.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_information',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalCarSystem.vehicleinformation'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_specification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalCarSystem.vehiclespecification'),
        ),
    ]
