# Generated by Django 4.1.3 on 2022-11-14 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalCarSystem', '0017_alter_rent_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='rentalCarSystem.vehicle'),
        ),
    ]
