# Generated by Django 4.1.2 on 2022-10-31 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalCarSystem', '0017_rename_address1_client_address_rent_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='discount_in_perc',
            field=models.SmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
