# Generated by Django 4.1.2 on 2022-10-31 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalCarSystem', '0019_alter_rent_deposit_alter_rent_km_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='rentalCarSystem.address'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='rentalCarSystem.client'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rentalCarSystem.payment'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='rentalCarSystem.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_information',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='rentalCarSystem.vehicleinformation'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_specification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='rentalCarSystem.vehiclespecification'),
        ),
    ]
